#!/bin/sh

set -eu

composer install

export PATH="$(pwd)/vendor/bin:$PATH"

cp .env.github .env

eval $(grep -v '^#' .env)

composer wp-install
composer install

if [ "${WPTT_INSTALL_DIR}" != "" -a -f "${WPTT_INSTALL_DIR}/web/wp-config.php" ]; then
    (
        cd .wp-install/web/
        wp server
    ) &
fi

composer test